DROP TABLE IF EXISTS `power`;
CREATE TABLE IF NOT EXISTS `power` (
  `node` int(11) NOT NULL,
  `power` double NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`node`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
