DROP TABLE IF EXISTS `thermostat`;
CREATE TABLE IF NOT EXISTS `thermostat` (
  `node` int(11) NOT NULL,
  `temp` double NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`node`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
